spring:
  datasource:
    url: jdbc:mysql://172.27.227.3/sell?characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  jpa:
    show-sql: true
server:
  servlet:
    context-path: /sell
  port: 8888